kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-gitops

bases:
  - ../../../03-tenants/01-example
  - ../../../03-tenants/02-vms
  - ../../../03-tenants/03-example-security

resources:
  - tenants-project.yaml
