apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"

resources:
  - ./namespace.yaml
  - ./operatorgroup.yaml
  - ./subscription.yaml

patches:
  - target:
      kind: Subscription
      name: compliance-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'release-0.1'
