apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-app1
  namespace: openshift-gitops
spec:
  destination:
    namespace: gitops-app1
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: apps/gitops-app1
    repoURL: https://github.com/apoczekalewicz/gitops-cluster-main.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
