apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: sa-pipeline
  namespace: example-helloworld-cicd
spec:
  serviceAccountRef:
    name: patch
  patches:
    sa-pipeline:
      targetObjectRef:
        apiVersion: v1
        kind: ServiceAccount
        name: pipeline
        namespace: example-helloworld-cicd
      patchTemplate: |
        secrets:
        - name: quay-creds
#        - name: github-creds
      patchType: application/strategic-merge-patch+json

