kind: Secret
apiVersion: v1
metadata:
  name: github-creds
stringData:
  .git-credentials: https://USERNAME:TOKEN@github.com
  .gitconfig: |
    [credential "https://github.com"]
      helper = store
type: Opaque
