kind: Secret
apiVersion: v1
metadata:
  name: github-creds
stringData:
  .git-credentials: https://apoczekalewicz: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@github.com
  .gitconfig: |
    [credential "https://github.com"]
      helper = store
type: Opaque
