apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- pvc/pvc-workspace.yaml

- configs/sealed-quay-secret.yaml
- configs/sealed-github-secret.yaml
- configs/sealed-signing-secrets.yaml

- tasks/task-cosign.yaml
- tasks/task-git-update-deployment.yaml

- pipelines/pipeline-example-helloworld.yaml
- pipelines/pipeline-example-helloworld-secure.yaml

