apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quay-creds
spec:
  encryptedData:
    password: AgB1Cj6shSj4raQZ8J1Uxa/q5hIAX3c7n34Pb/wSQbhaMI9S4ej/HOATDsZTmQhc85zJaZdxtuEdpeCizhwv5ZQ/G4PGYbIhXH+0pKfQcwBxeb+X2By2+6Kmb38/n0/PgeB6kd361Hh4TjwF0deqcy/RAXDd1FWAVdSyCfuT9pzcPanWzvXYz8ebpoymhnyIqk6ry9455klj4LKf6/i43/P7z2qh76Xu9m61+aiVSKo7It0LU3kHze3YuE0GcNILoibjt63siLRMCD+teaRQvdcbCSN3UNyzaNeFg2O6/OZNcQqxLQhnb6m/DKeff9OlOra/wQfJpJrH66vBDhNEqPH9sEQ/JnJogYSKTKQivSxteRZ2AmgWbHEUtu9voPLP9yDRgssqOb14Oz+K0NLUDDB8Wkk98ERDmOkx7k0xUTI49SGsgcPPoUfOpIGGX47++YG5+cQD4w2jNbzZIGKOj/xgGBrXTF6Eikape/x/DWHVrBBeEJgYn9j6umbJoD/oSXwRn+uPUv2wdXdIwjShcWLYwkTOtdHbl/IUFfImGg+J02pXMX4wtjdxgtFV8uCsEzoq98tEcm7KhmAs9OqI6EX+dKD0IFZnX58QesY2kKA697oI3u9aNsKk5B7YZc3sL1NJZyj71GYcOVLF3+YHqX3KhSCwHS7NJwv67L1jtDf+zHG/COyswedtI+GJRM4v+UkDs+/BCMFM64C8p0mZ66fY7tJBUtxqeL+yQQ==
    username: AgB/mvBraKThuknD3XY0axkhujMhXSDopurQUjnB5D0u7w1tR0dgAyTQWjwZmQJEDvtaL06bZe3sXgQgAwVhqXc0+klwz7M0o8FV6NYprgMo+9XS4Pvgb6wAYedAO0ZFMII7mgYWI6HMNNU/7ofDsVcIA3QHGQ3ZN8tUJ0rhVjvtymLjRVWDUsHsdqUp0bijpcrwyYOVynrRkzAFhEejl46VFHOFti3lEgyu8T/Wg4s6facwA0i260kQCt0b/FssvuN+m1l+UIesXVUyfXjdJwb50ymj6aQKckOj5xR1EnUwZlaAkgi/yqCRwkoJ0KJHHPEIHwsnGtUXbZjwQcc8fqJcYK+4wz1VNU7XycBqIMmcYB4lzfkgZdLIFufD2FfAPgEObSoIuNHfOYdb93TnkHSXVhLP8sJrj8PJaszfrjgNpSvYA3gi1bPI6adc2vGI2qOtFlBA0sgq/OYKRHRtGs7Krp9N88IswQ5G1D1ITb9UrOncd4UKfL9Ag8x+HysGO6sXMR5A/YDc823sB6QD2E5GxnDa1XnyZcjgyb2n7FW4xCNEO6XmwCQ9a7xmGC7Z4gs9e89An2T4HxzVmQzgWkcjDtkeVX8Jtlme+a31bp+DM6SmKqVbsQKaej7h8BB3EDX2MXzudiRWbKnIc3O9AHMhW5YlExMBDDLKLO8zgRYVt1/A7kjVySOkvid/M+XKfpDUK4LavGm29JPm6nMFJ0ZKoxKbbXf5SuQwl9CvSvzbsLIfptAgVTIFZ9SwPElY4qD6oMtW736JDg5MWoMS6RJi
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/docker-0: https://quay.io
      creationTimestamp: null
      name: quay-creds
      namespace: sealed-secrets
    type: kubernetes.io/basic-auth

