apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: quay-creds
spec:
  encryptedData:
    password: AgAxN6/Wj/LyYyNmrd/hI3oxnIe8mRCUH6VryxHw2nP3vT/tPmCzQWiTiWAWhXdwMnNf+SL3Mna2SziEeOFNl3Qrtt6ottZjRjX/1Jqn40dV86e5RRoOWDXYvAkfvGvZxS3Ons/5fm3UL/LqMHU9ZG4E5RMfcVBu0BAGWV01zVCXgNUi1YCq44FjbuLZX6jvJ4pbkXtN3ZYmnU/Abg+Bc3iQFEmsXKZxjEIenDd1WZngtGEycYpGR0AmbDVKis9kQ3URF0HkO/Bwxvi4teb7rcl/8CfUpBoqsi5aE5tKZDBhMGpCzlqzCwN1YaLX0JU6fOAkuCXbszO4534FbbQF13VYslWmQtn012SUNecReP4Ea/xwDo61SdwbA4kTlBx3Y9cuYG2LZVAaDJJh45MzU3XqE9SCCdDRyuo607oxAY37EzTX+4gBOX+3uK1rLOtamZbatrxSdX+F7kXnEFjlwTVLasWGGWbhjZOMxCCz6uMAanQtMje1RVQNlH8PCcDedtuWQnojdbFTn00BS2bFwQ3HIzbtVWKtLnVWuqsxAteSd6O/O2aVsRQdfeOCY12oSqiMmdNfP+2RxCXjSAYB2+SERqdbC8B0ga+WbnZsSuM1/waY70oFOiR4epwHPDkogmdV3taqmo1nFRWQfYRW4Sqsk1CQGljLfBEC5AvS8dv/Vdr4qytPF7aBy/wj3qkCw3hRWDmbZMT3s96byVVnv4FOgso5aWhWw5iVLH/vVDOpJMvM0zdkKD5rYE1/S8T6LPn1cOgUED0PiBVWqvVb1aiU
    username: AgAVafl5vYVSyEp8ZsbhoZA67zqdqOsU53jRdVMPanSl3W0bWGHm5f0iaajrbUdexUHI4SGZOIuwirqgFx5BgD0wUbsKxq6s1xX8H+K+5aH4KB/JAC1yWJkieHHNvWWh0TQbeqIyZyHYyF2VdxDRsBUKkJUEtzZLZR0KZB6kbFPddd87MKvOp1HI+ZJtMs/knTOmHtE/ZAD+T1pW2DDTFhZVyUrqAIzkOI9cquMZBVFTT2HWVsfv6KIQfJt9rJPT5vWmbMg9Vru059lt5ZZ3O7oIqT8nzVXQiZaGfvfIAswSsd9ujtzuf8T3abk49PWfXUzaTqlHji2hvBfmOKL3YnDIDFKqvrRemIutnQX1Q8sobC2Wq+W7GpJY9lrHh5DPps9P0W2VfacD8Zun1NjUnkGCvL+INalghTCUrRKq6kaTPR4kI+8MZISQPD/W31QjVGtsoeLyfSMfDp+j+wwl/nRiToZl8c9/GvmvGUIW/mM0Ec1aLY57CujCtuFORM07THrJItNV0XvKl3sOPIKpKT46uScfrBAaPJ+mUdX20eeprqVuurgPpCjUuuefrR4czfRcNkKHJZ+SzndzLr+vcTrpbaRnNWbtyHEchVIFYxofd6vQh2+WGqM40WIaCpP38KZ8EBpDjt7erQ1M4b2ffnZtBYTf/w9VtA8EyGRPoFQVDEqpG0hk8X4gp4rgwVreYzWhXvur4vk8tSeXhL1YICPP/OpIm/xGm975Lw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/docker-0: https://quay.io
      creationTimestamp: null
      name: quay-creds
    type: kubernetes.io/basic-auth

