apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: github-creds
spec:
  encryptedData:
    .git-credentials: AgBNQ0eoTiOEd0PANPIDApYkZWNy5g+4wnTdcnAYVBag6c5FSXRAgdK5QVOGjCqECHdBsZLFeHFdHu0nrXWg2cVlWVdDRKNyxZ1bPS/jN1X4ZYsH7q7oqoOt5AU1t3yF4KiyuTTAGlskwUlZDKQBf4nsEtaEuxtvLGAlamECgDfU9n0v3C5Kh4aAGFiJfJnCVZqgRmOyVbiwoG4fJp5p7GBLAJWIaiFtyup2vEma6zUXgrz141ctSxL2x4szGsnP4UDSuLcHoV3iNRFCOFF28Cledun/NAl33B+Yg3mU1U/C7aCDoHmlkRDqAPAsYisgTcIgL63LoNyXWQkW6oLPJpdcan6echytuqyLYwUZ7wl7PhgT7PG2NLtb3Rbc2fq2lRRnU+/c2IyS65IqO1BkDuNsG8eNMdtyIDa/KHqV9cNHs5DqhTIWe6elF2+9c6M5mt4I2nUcrAH+YhOx223FFtas0YET5C0jVNh+T77NLDrntjezAQ1kMfRMowMZVaDFFAspexLJdOWf8x0q2PF1V9kjoUUdISjbFsrcHSMSKJYvYPz2UL4LDFN7ITcWP1Yr5al4dHNkO0zffryqS/VPq4q4/89Sg3nNCBSbl2rUzbFCVUStmlkcz5oAnyC7Se9Use3A5jt5d6InXXIPjb+0b5ksgUNBPnT1exwHb7qXgUhCpw1X7MAP88kzlwTLqHaDXVXFV1+npwHX0+CgeBxwQD0a3KW4Fyfnvo8gj2f9Pf9iEcJlEpcXGIKv65YHC3AXw05DPpRFsWy+95Acr2Bw+MdA9CSAy3uzmG5jsw==
    .gitconfig: AgA1JTVvRTKbouauaY+KkfSPj46jVtQ2Z/j51KdSwfWt/8Vuj8WkTvxMOy/yNryYGmiTvH2OqiVzWKeEvrgcXBsdde5SIBC11//tCoBmlZ6KS58eWtBeI8zp2KMYLfiGqBPYeUFyYBSo/2aawT9q0Tl6vY3j8EJXOsJwuXJ6E2YvOE5Ed2dhLs1UT2hMX4MKnEKCrgOf/lJkKqmolDkRjf9jL7Khzswtmai8HQzKM8i24K3qNSQMopBZ07GOJIqo0f1EunKU1xstooNzXJ6gy/B5J7pt4WTKqZKpyoYCTsVL8xuYyi298hMTszcLt+Fu6he1teeNroIF9P6dZsOVD4+tAAy6b395Co5cRt/aNMW+ltJJvvVAc+9nW0fweqalfcq+boqXJ4QllApsgJCAHf6BDmR3+uwt6FM3+D8IjmvTo4ROSH2qAs8yieIukHWptsHvxwu+z+zYuq5zlJ2zBQC9sADlu0KB80kNPfcRDoDoOkCs5A/GE3Z4O5Oy58CREjkgqh25jeTS5Qqp2/J6Ls2th5CJF8RXNZRKMT4CcyPhCi3612lTb0fqGTFJMKIWVo5ukj+d4iNMG+7NpF6NxvhaKv/YKorIs53Wv8otzR1AixKWn1LJeuR3cIW71bbljyowKBDkv6GuXd+oa9P5Q23BXMH80Yz+k0Q1H+Ib2eTmEXCodBZCDxDcHwZlRVe/SNSoAIRT6p6LlOoHBoA82+E2MVMNr8t3uPakdQhf81w+XOUM8coHYCgkjBAbKNSenPXomsI=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: github-creds
    type: Opaque

