apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: crda
spec:
  encryptedData:
    crda-key: AgC7VUUMIkJNJM6vV6b6D9I/x2iyl1hXONGn/GNmUvbWB35zpB1/lwRPNQO12xhUXnxpoV5AShH+u7+/XwzBXzM8dYwU+YcCtSRjDnoP1OAc2SWpFMJLzDNciCklYdSOSKzLgg9Ii1aII+GypYpFvePz8GBjlDxpvOVoIQsoCLjrcF0vdag9qFsaLDnJzLdNdQp6pSr3MQcFpf9TmUwSRqHu8PCANa3+Gvj6RX50JkRa8mOt2JAIv9TiEJd8iNkKYQDYIuFjIZtKS1NQy33GEdkdEfHziapz22rw7BhhHli2mfhPfcGxSEXl2zUsbpPyoLaI65daTkE44Ao3mrWIy+X4UqqLkt/OJBDytG/aVYswlEmnXy2Na/5HpHG0+YLkf1H2WsSje8KaO55QIwB7eAyIv2OnufOn2G4sjIkAGzvINoa+n3RktKGyykTSoY1xHErNI1uuTXBOk8/EBxRWKmOk5PBs1J4N7usoiz8anKwx85VaC7TTzTw8HljWu0ZEcb7quWhNlYGRwzt6I11ZqumEDGWOTMJwLccjfJigS3ruk3VGEXpASw0v6n+VqSG8MsawtPSt9xwJE/xcLtYY0QTTiFJ4bKa6ZGLv9CFuCQDkCxY1O9BDlgoDsoeV8u9qtNlv4f5XqHcqSkbHg6TPAwje4MGHq5BhstUM0C7TkXWoTI+SqgH3hAssIyIt/VsUMs18b8dLoy/cT8EnaT7V3kRQsCF7IuPe3e04j4gxPkelJfAMjgg=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: crda
    type: Opaque

