apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-compliance

bases:
  - https://github.com/redhat-cop/gitops-catalog/jcompliance-operator/operator/overlays/release-0.1?ref=main
