apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-cnv

bases:
  - https://github.com/redhat-cop/gitops-catalog/virtualization-operator/base?ref=main

patches:
  - target:
      kind: Subscription
      name: kubevirt-hyperconverged
    patch: |-
      - op: replace
        path: /spec/installPlanApproval
        value: 'Manual'

