apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  argocd.argoproj.io/sync-wave: "2"

namespace: openshift-storage

bases:
  - ../../base
  - github.com/redhat-cop/gitops-catalog/openshift-data-foundation-operator/config-helpers/node-labeler/overlays/default?ref=main

resources:
  - storagecluster.yaml
