apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: odf-sc-labeler
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
rules:
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
    verbs:
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odf-sc-labeler
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-5"
subjects:
  - kind: ServiceAccount
    name: odf-sc-labeler
    namespace: openshift-storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: odf-sc-labeler
