apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - install.yaml

patches:
  - target:
      kind: Subscription
      name: advanced-cluster-management
    patch: |-
      - op: replace
        path: /spec/installPlanApproval
        value: 'Manual'

patches:
  - target:
      kind: Subscription
      name: advanced-cluster-management
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'release-2.6'

