apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: sonar-properties
spec:
  encryptedData:
    sonar-project.properties: AgANOWuS5gPcVsj5xV0OaHRsj45nbmQGg47LAaVp2rJ4dZVfznU6c4Q6IbqeJXfsrK+rFHG3gksCUu+VdOsptOEbECCYUlJjyjPKat6613U207DrVm0GCT0SDdUsz6KmOlAG6zKepqfngI3JgGrS1h/zSCEgkeQVW8ADoNMNhFCKkMjxvzbv0xyfTGws/Z9jxFmtQX/JzXo30m2bXByIpe2AYBlBLdGzDYb3WaHyZmjts0GwNWuJoul7atl4D3VPiZBDYf2larf2c5rKSSO79qqc4g3xZeejolw0u1j5etqVxPzIkmR8nn9lRhiiYZ6OfW2gq3S2LAR8M14Acw+bxPqYKY+zH8NAMmf3p3O6+TGXzgddz/WctJG4NjQBgO2qk27hLNjHFyxgfeuBZIT8TQFHN5EP2jS1W5WuUS8qWnbWfcdzpqG7WUwAngAWG0aM95yKONH3W/cBkhH2yNod4JbSd8Y19aokU09dl36KnfTUmj300o/MRHxWhgSfgaOFv/fUUSqKbiDSTdqfdYyIteMKbzrr7mytIK0ym+5YokhX2bnE+hsrB88PSst43ugircKam2PaYzqMN95ER4yap+IEV1MYRTmSTjwq12VvxkmN1damIYN0pVbUz3na0263XrtSAuredMjzGjGbWFlgmAaWaRnDhYR05EWF+ysesDsWec8lIN0E5q31ZqABQMEIXuh9erxY5OgN2wVk+fW3PAnZsaXbtR90vK6MP18k/q3fD+rr9GGYukJIb9zdhkVfC8p5jm7zdRAzU1mOzPGAOQWcY9RMr4T60ShQnh1+HxN9DLfXKeI/CV45njjX2IqUDzFoqDuf3TxcG7oGhOzjIhHjmS+/pPbQQHDTS8zkh7jknrISpLiXCaka634sCllZaD+DWuNeLzvVRjoqz+3BkWRSgwWI9Bvqk1YyW42clKy+boQO1ZcRuhRg
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: sonar-properties

