apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: sonar-properties
spec:
  encryptedData:
    sonar-project.properties: AgBq5LBnUy6CMp5YgRg/e/UMEu3/9HUICq66OGz5UEakvajtwXpUJE8W6GnAPkc22pCK7phG53noE6Zgf7aFmKPTjMEyN4yT+TuKE+3SRdbUYMXS90ditw38D8KhmpObzdalgBgOfK8UaEhuBPTbjC15g6s3I44swYlsuUGKDROds2tHt/iQ1E6tf4bFYavgsIm+XcHhpMCEBWkRrEGxjFSVGFBC+osCL8ki6XQckkKsHPwhNDNTqPFVmj1m55EohC1S0t4axsdg6th9WK0XKK+awSzlD4zibjVj6b+69goIs2oHSPRXWNQTWXYAw1cGHj2mvevrsfSMMVBgklWToniM7GWX9NFK8DhE0X0zoAODDId7Q3KSwWCjdBit9WtdoVDDjbWSl0E2gDrLDXGOxOVK/MacBih4rT3xIgM5Y7p6tFIs4vz6nAhIAu1ByjTBBGaqmY3Aujt8nUX9/A5s3Z5nQZN2lF1cBv9EUGdC273q/cWbXg0t48GuiBHURrN/v2/GJ+0xtyZMeOPbyY0W6mjkn529jJnMQgV76Xwhod/mvLIMuVEU7DisG3f37jcf8TS2SIegXXdNbO7KDa//MjLCsBCQkMKAQTrrQRE/j2ofmKhdY8HLhnpnKVK4p8fjeWuHHgp5BFf551LcV/YNDwG8n+p5FydFDc5Z5prfBSuDwT+dTY3rLkzGjJwtOC7SvDv134KNlb9jDrqofbeCkvbglxYrKPDnJu3atK8PRNLo3s6fHWaJnxWXIIOTMeAuzKmyLNPivvFMB6A1Squ9sEm6Oxw6rfHpqRiQRDl0QNjEJw+kxoM7v72JliL1yZx0YZlqd/tgpj3uk4dolxwJHlkUsz5KXJOKuzNGmhJRnlfZZauLg/m5IlSNppFJM/g33FOebNX1tClJK0JNiH7fGZemf+3dxFFiYrAanUp26/NjXrmOSGuytt/9Rnyf/N5ZdBGELsyI04peIvPQYA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: sonar-properties

