apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: sonar-properties
spec:
  encryptedData:
    sonar-project.properties: AgCat7D5GdJga5kPViDijMDmukpWbSSOYFOy8A9WoD4S8ErOpwRlKWjn+bz0WXISMgRsrKLFQCTOQtcjt2D9+e8mE+32mo7UsJZmWksgQgP6O+ad4GVVvea9Ri4KALd7OGG6WeCcYBSwbC5yz+HdWN/su+y0ZUbRyU2HCQS2Y0jIpKZOTXmmgD/n/wPvuDgbY+v01Qno9BroT8sqFHjzFc+Y6xmd6Y+5/Jg1nuLA2zX4zw8T1Ai4FFY4hLSPPF4w/a/avkMarNdOlb3Xx+Ev0ywtSR/kz9KhZzzO8feEl/UCC/KmZIfDbw/U/CUBiEsqAxRXLS+AckrubXVvr0IeBnK2w7+7Km1CYZ1vRHhWwHO8upACE2f8l1GM0ywGCDhAxVgOqHbONwRbVaIBSovVOMzyFYAl8fgMRZMDbC4/fkk4xW47yX7F5nUrecuZ+/ZhPd5avqcypVXu6IrpMkrUFBaWTfcyJ0P2XKLVWuQDmiQHZ8nZ3k4fuSxWlewGEr4JiX33VLQSC2v2Ivvcd2JtAQ+cgmD35Y7bHybvA18HybI2M2rjxrT8VRRpElqr7ZKSzLGJc3ejl1DsHb7mEe5+oTfLRbhy3gmOcKEVFO0DGkdXIwg1jMQqes9v6Y6S8X6uDLKCd5DGOL+xYw0aAnlZFn9SEvynaan0vPIEZwMyaj/+QniRtqWBtIsDvtUtzfEkywWiUZvryLMQBNzY4ylJXRokSm7glRitgcC9YNojQyUo0LYUcB2uB4G31IIaJ9QqDTj+2RjYwSNeYz4bHDSGong0WgJU1DJ4CslQeoCJlfd5qotLkNlq9RJNp6Z1SMb5YAK+b8aHFzA8m2pbVGoePdLaypwa+6q/557slIuYeuq4CrxNE4OJP8eywu/08b13QjI0kg+HQihE7zlmWcKHMIkLIwqtG9hRS0mM5LG/oHbYVpYwwtM24jNCg/lbatXbmmKkXE0TqGtQcJo8RQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: sonar-properties

