apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - operator
  - instance

patchesJson6902:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: ansible-automation-platform
      namespace: ansible-automation-platform
    path: patch-channel.yaml
