apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  argocd.argoproj.io/sync-wave: "2"

namespace: openshift-storage

resources:
  - job_change_default_sc_annotation.yaml
  - rbac.yaml
  - service-account.yaml
